### YamlMime:ManagedReference
items:
- uid: NMF.AnyText.Rules.RuleApplicationMigration
  commentId: T:NMF.AnyText.Rules.RuleApplicationMigration
  id: RuleApplicationMigration
  parent: NMF.AnyText.Rules
  children:
  - NMF.AnyText.Rules.RuleApplicationMigration.#ctor(NMF.AnyText.Rules.RuleApplication,NMF.AnyText.Rules.RuleApplication)
  - NMF.AnyText.Rules.RuleApplicationMigration.New
  - NMF.AnyText.Rules.RuleApplicationMigration.Old
  langs:
  - csharp
  - vb
  name: RuleApplicationMigration
  nameWithType: RuleApplicationMigration
  fullName: NMF.AnyText.Rules.RuleApplicationMigration
  type: Struct
  source:
    remote:
      path: AnyText/AnyText.Core/Rules/RuleApplicationMigration.cs
      branch: main
      repo: https://github.com/NMFCode/NMF.git
    id: RuleApplicationMigration
    path: src/AnyText/AnyText.Core/Rules/RuleApplicationMigration.cs
    startLine: 13
  assemblies:
  - NMF.AnyText.Core
  namespace: NMF.AnyText.Rules
  summary: Represents a migration from an old rule application to a new one
  example: []
  syntax:
    content: 'public record struct RuleApplicationMigration : IEquatable<RuleApplicationMigration>'
    content.vb: Public Structure RuleApplicationMigration Implements IEquatable(Of RuleApplicationMigration)
  implements:
  - System.IEquatable{NMF.AnyText.Rules.RuleApplicationMigration}
  inheritedMembers:
  - System.ValueType.Equals(System.Object)
  - System.ValueType.GetHashCode
  - System.ValueType.ToString
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.ReferenceEquals(System.Object,System.Object)
- uid: NMF.AnyText.Rules.RuleApplicationMigration.#ctor(NMF.AnyText.Rules.RuleApplication,NMF.AnyText.Rules.RuleApplication)
  commentId: M:NMF.AnyText.Rules.RuleApplicationMigration.#ctor(NMF.AnyText.Rules.RuleApplication,NMF.AnyText.Rules.RuleApplication)
  id: '#ctor(NMF.AnyText.Rules.RuleApplication,NMF.AnyText.Rules.RuleApplication)'
  parent: NMF.AnyText.Rules.RuleApplicationMigration
  langs:
  - csharp
  - vb
  name: RuleApplicationMigration(RuleApplication, RuleApplication)
  nameWithType: RuleApplicationMigration.RuleApplicationMigration(RuleApplication, RuleApplication)
  fullName: NMF.AnyText.Rules.RuleApplicationMigration.RuleApplicationMigration(NMF.AnyText.Rules.RuleApplication, NMF.AnyText.Rules.RuleApplication)
  type: Constructor
  source:
    remote:
      path: AnyText/AnyText.Core/Rules/RuleApplicationMigration.cs
      branch: main
      repo: https://github.com/NMFCode/NMF.git
    id: .ctor
    path: src/AnyText/AnyText.Core/Rules/RuleApplicationMigration.cs
    startLine: 13
  assemblies:
  - NMF.AnyText.Core
  namespace: NMF.AnyText.Rules
  summary: Represents a migration from an old rule application to a new one
  example: []
  syntax:
    content: public RuleApplicationMigration(RuleApplication Old, RuleApplication New)
    parameters:
    - id: Old
      type: NMF.AnyText.Rules.RuleApplication
      description: the old rule application
    - id: New
      type: NMF.AnyText.Rules.RuleApplication
      description: the new rule application
    content.vb: Public Sub New(Old As RuleApplication, [New] As RuleApplication)
  overload: NMF.AnyText.Rules.RuleApplicationMigration.#ctor*
  nameWithType.vb: RuleApplicationMigration.New(RuleApplication, RuleApplication)
  fullName.vb: NMF.AnyText.Rules.RuleApplicationMigration.New(NMF.AnyText.Rules.RuleApplication, NMF.AnyText.Rules.RuleApplication)
  name.vb: New(RuleApplication, RuleApplication)
- uid: NMF.AnyText.Rules.RuleApplicationMigration.Old
  commentId: P:NMF.AnyText.Rules.RuleApplicationMigration.Old
  id: Old
  parent: NMF.AnyText.Rules.RuleApplicationMigration
  langs:
  - csharp
  - vb
  name: Old
  nameWithType: RuleApplicationMigration.Old
  fullName: NMF.AnyText.Rules.RuleApplicationMigration.Old
  type: Property
  source:
    remote:
      path: AnyText/AnyText.Core/Rules/RuleApplicationMigration.cs
      branch: main
      repo: https://github.com/NMFCode/NMF.git
    id: Old
    path: src/AnyText/AnyText.Core/Rules/RuleApplicationMigration.cs
    startLine: 13
  assemblies:
  - NMF.AnyText.Core
  namespace: NMF.AnyText.Rules
  summary: the old rule application
  example: []
  syntax:
    content: public RuleApplication Old { readonly get; set; }
    parameters: []
    return:
      type: NMF.AnyText.Rules.RuleApplication
    content.vb: Public Property Old As RuleApplication
  overload: NMF.AnyText.Rules.RuleApplicationMigration.Old*
- uid: NMF.AnyText.Rules.RuleApplicationMigration.New
  commentId: P:NMF.AnyText.Rules.RuleApplicationMigration.New
  id: New
  parent: NMF.AnyText.Rules.RuleApplicationMigration
  langs:
  - csharp
  - vb
  name: New
  nameWithType: RuleApplicationMigration.New
  fullName: NMF.AnyText.Rules.RuleApplicationMigration.New
  type: Property
  source:
    remote:
      path: AnyText/AnyText.Core/Rules/RuleApplicationMigration.cs
      branch: main
      repo: https://github.com/NMFCode/NMF.git
    id: New
    path: src/AnyText/AnyText.Core/Rules/RuleApplicationMigration.cs
    startLine: 13
  assemblies:
  - NMF.AnyText.Core
  namespace: NMF.AnyText.Rules
  summary: the new rule application
  example: []
  syntax:
    content: public RuleApplication New { readonly get; set; }
    parameters: []
    return:
      type: NMF.AnyText.Rules.RuleApplication
    content.vb: Public Property [New] As RuleApplication
  overload: NMF.AnyText.Rules.RuleApplicationMigration.New*
references:
- uid: NMF.AnyText.Rules
  commentId: N:NMF.AnyText.Rules
  href: NMF.html
  name: NMF.AnyText.Rules
  nameWithType: NMF.AnyText.Rules
  fullName: NMF.AnyText.Rules
  spec.csharp:
  - uid: NMF
    name: NMF
    href: NMF.html
  - name: .
  - uid: NMF.AnyText
    name: AnyText
    href: NMF.AnyText.html
  - name: .
  - uid: NMF.AnyText.Rules
    name: Rules
    href: NMF.AnyText.Rules.html
  spec.vb:
  - uid: NMF
    name: NMF
    href: NMF.html
  - name: .
  - uid: NMF.AnyText
    name: AnyText
    href: NMF.AnyText.html
  - name: .
  - uid: NMF.AnyText.Rules
    name: Rules
    href: NMF.AnyText.Rules.html
- uid: System.IEquatable{NMF.AnyText.Rules.RuleApplicationMigration}
  commentId: T:System.IEquatable{NMF.AnyText.Rules.RuleApplicationMigration}
  parent: System
  definition: System.IEquatable`1
  href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  name: IEquatable<RuleApplicationMigration>
  nameWithType: IEquatable<RuleApplicationMigration>
  fullName: System.IEquatable<NMF.AnyText.Rules.RuleApplicationMigration>
  nameWithType.vb: IEquatable(Of RuleApplicationMigration)
  fullName.vb: System.IEquatable(Of NMF.AnyText.Rules.RuleApplicationMigration)
  name.vb: IEquatable(Of RuleApplicationMigration)
  spec.csharp:
  - uid: System.IEquatable`1
    name: IEquatable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  - name: <
  - uid: NMF.AnyText.Rules.RuleApplicationMigration
    name: RuleApplicationMigration
    href: NMF.AnyText.Rules.RuleApplicationMigration.html
  - name: '>'
  spec.vb:
  - uid: System.IEquatable`1
    name: IEquatable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  - name: (
  - name: Of
  - name: " "
  - uid: NMF.AnyText.Rules.RuleApplicationMigration
    name: RuleApplicationMigration
    href: NMF.AnyText.Rules.RuleApplicationMigration.html
  - name: )
- uid: System.ValueType.Equals(System.Object)
  commentId: M:System.ValueType.Equals(System.Object)
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  name: Equals(object)
  nameWithType: ValueType.Equals(object)
  fullName: System.ValueType.Equals(object)
  nameWithType.vb: ValueType.Equals(Object)
  fullName.vb: System.ValueType.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType.GetHashCode
  commentId: M:System.ValueType.GetHashCode
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  name: GetHashCode()
  nameWithType: ValueType.GetHashCode()
  fullName: System.ValueType.GetHashCode()
  spec.csharp:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
- uid: System.ValueType.ToString
  commentId: M:System.ValueType.ToString
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  name: ToString()
  nameWithType: ValueType.ToString()
  fullName: System.ValueType.ToString()
  spec.csharp:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.IEquatable`1
  commentId: T:System.IEquatable`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  name: IEquatable<T>
  nameWithType: IEquatable<T>
  fullName: System.IEquatable<T>
  nameWithType.vb: IEquatable(Of T)
  fullName.vb: System.IEquatable(Of T)
  name.vb: IEquatable(Of T)
  spec.csharp:
  - uid: System.IEquatable`1
    name: IEquatable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.IEquatable`1
    name: IEquatable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.ValueType
  commentId: T:System.ValueType
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype
  name: ValueType
  nameWithType: ValueType
  fullName: System.ValueType
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: NMF.AnyText.Rules.RuleApplicationMigration.#ctor*
  commentId: Overload:NMF.AnyText.Rules.RuleApplicationMigration.#ctor
  href: NMF.AnyText.Rules.RuleApplicationMigration.html#NMF_AnyText_Rules_RuleApplicationMigration__ctor_NMF_AnyText_Rules_RuleApplication_NMF_AnyText_Rules_RuleApplication_
  name: RuleApplicationMigration
  nameWithType: RuleApplicationMigration.RuleApplicationMigration
  fullName: NMF.AnyText.Rules.RuleApplicationMigration.RuleApplicationMigration
  nameWithType.vb: RuleApplicationMigration.New
  fullName.vb: NMF.AnyText.Rules.RuleApplicationMigration.New
  name.vb: New
- uid: NMF.AnyText.Rules.RuleApplication
  commentId: T:NMF.AnyText.Rules.RuleApplication
  parent: NMF.AnyText.Rules
  href: NMF.AnyText.Rules.RuleApplication.html
  name: RuleApplication
  nameWithType: RuleApplication
  fullName: NMF.AnyText.Rules.RuleApplication
- uid: NMF.AnyText.Rules.RuleApplicationMigration.Old*
  commentId: Overload:NMF.AnyText.Rules.RuleApplicationMigration.Old
  href: NMF.AnyText.Rules.RuleApplicationMigration.html#NMF_AnyText_Rules_RuleApplicationMigration_Old
  name: Old
  nameWithType: RuleApplicationMigration.Old
  fullName: NMF.AnyText.Rules.RuleApplicationMigration.Old
- uid: NMF.AnyText.Rules.RuleApplicationMigration.New*
  commentId: Overload:NMF.AnyText.Rules.RuleApplicationMigration.New
  href: NMF.AnyText.Rules.RuleApplicationMigration.html#NMF_AnyText_Rules_RuleApplicationMigration_New
  name: New
  nameWithType: RuleApplicationMigration.New
  fullName: NMF.AnyText.Rules.RuleApplicationMigration.New
