### YamlMime:ManagedReference
items:
- uid: NMF.Models.Security
  commentId: N:NMF.Models.Security
  id: NMF.Models.Security
  children:
  - NMF.Models.Security.ModelHasher
  langs:
  - csharp
  - vb
  name: NMF.Models.Security
  nameWithType: NMF.Models.Security
  fullName: NMF.Models.Security
  type: Namespace
  assemblies:
  - NMF.Models
references:
- uid: NMF.Models.Security.ModelHasher
  commentId: T:NMF.Models.Security.ModelHasher
  href: NMF.Models.Security.ModelHasher.html
  name: ModelHasher
  nameWithType: ModelHasher
  fullName: NMF.Models.Security.ModelHasher
