### YamlMime:ManagedReference
items:
- uid: NMF.Expressions.IncrementalizationConfiguration
  commentId: N:NMF.Expressions.IncrementalizationConfiguration
  id: NMF.Expressions.IncrementalizationConfiguration
  children:
  - NMF.Expressions.IncrementalizationConfiguration.Configuration
  - NMF.Expressions.IncrementalizationConfiguration.Configuration.ConfigurationChildrenCollection
  - NMF.Expressions.IncrementalizationConfiguration.Configuration.ConfigurationReferencedElementsCollection
  - NMF.Expressions.IncrementalizationConfiguration.ConfigurationExtensions
  - NMF.Expressions.IncrementalizationConfiguration.IConfiguration
  - NMF.Expressions.IncrementalizationConfiguration.IMethodConfiguration
  - NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy
  - NMF.Expressions.IncrementalizationConfiguration.MethodConfiguration
  langs:
  - csharp
  - vb
  name: NMF.Expressions.IncrementalizationConfiguration
  nameWithType: NMF.Expressions.IncrementalizationConfiguration
  fullName: NMF.Expressions.IncrementalizationConfiguration
  type: Namespace
  assemblies:
  - NMF.Expressions.Configuration
references:
- uid: NMF.Expressions.IncrementalizationConfiguration.Configuration
  commentId: T:NMF.Expressions.IncrementalizationConfiguration.Configuration
  parent: NMF.Expressions.IncrementalizationConfiguration
  name: Configuration
  nameWithType: Configuration
  fullName: NMF.Expressions.IncrementalizationConfiguration.Configuration
- uid: NMF.Expressions.IncrementalizationConfiguration.Configuration.ConfigurationChildrenCollection
  commentId: T:NMF.Expressions.IncrementalizationConfiguration.Configuration.ConfigurationChildrenCollection
  name: Configuration.ConfigurationChildrenCollection
  nameWithType: Configuration.ConfigurationChildrenCollection
  fullName: NMF.Expressions.IncrementalizationConfiguration.Configuration.ConfigurationChildrenCollection
  spec.csharp:
  - uid: NMF.Expressions.IncrementalizationConfiguration.Configuration
    name: Configuration
  - name: .
  - uid: NMF.Expressions.IncrementalizationConfiguration.Configuration.ConfigurationChildrenCollection
    name: ConfigurationChildrenCollection
  spec.vb:
  - uid: NMF.Expressions.IncrementalizationConfiguration.Configuration
    name: Configuration
  - name: .
  - uid: NMF.Expressions.IncrementalizationConfiguration.Configuration.ConfigurationChildrenCollection
    name: ConfigurationChildrenCollection
- uid: NMF.Expressions.IncrementalizationConfiguration.Configuration.ConfigurationReferencedElementsCollection
  commentId: T:NMF.Expressions.IncrementalizationConfiguration.Configuration.ConfigurationReferencedElementsCollection
  name: Configuration.ConfigurationReferencedElementsCollection
  nameWithType: Configuration.ConfigurationReferencedElementsCollection
  fullName: NMF.Expressions.IncrementalizationConfiguration.Configuration.ConfigurationReferencedElementsCollection
  spec.csharp:
  - uid: NMF.Expressions.IncrementalizationConfiguration.Configuration
    name: Configuration
  - name: .
  - uid: NMF.Expressions.IncrementalizationConfiguration.Configuration.ConfigurationReferencedElementsCollection
    name: ConfigurationReferencedElementsCollection
  spec.vb:
  - uid: NMF.Expressions.IncrementalizationConfiguration.Configuration
    name: Configuration
  - name: .
  - uid: NMF.Expressions.IncrementalizationConfiguration.Configuration.ConfigurationReferencedElementsCollection
    name: ConfigurationReferencedElementsCollection
- uid: NMF.Expressions.IncrementalizationConfiguration.ConfigurationExtensions
  commentId: T:NMF.Expressions.IncrementalizationConfiguration.ConfigurationExtensions
  parent: NMF.Expressions.IncrementalizationConfiguration
  name: ConfigurationExtensions
  nameWithType: ConfigurationExtensions
  fullName: NMF.Expressions.IncrementalizationConfiguration.ConfigurationExtensions
- uid: NMF.Expressions.IncrementalizationConfiguration.IConfiguration
  commentId: T:NMF.Expressions.IncrementalizationConfiguration.IConfiguration
  parent: NMF.Expressions.IncrementalizationConfiguration
  name: IConfiguration
  nameWithType: IConfiguration
  fullName: NMF.Expressions.IncrementalizationConfiguration.IConfiguration
- uid: NMF.Expressions.IncrementalizationConfiguration.IMethodConfiguration
  commentId: T:NMF.Expressions.IncrementalizationConfiguration.IMethodConfiguration
  parent: NMF.Expressions.IncrementalizationConfiguration
  name: IMethodConfiguration
  nameWithType: IMethodConfiguration
  fullName: NMF.Expressions.IncrementalizationConfiguration.IMethodConfiguration
- uid: NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy
  commentId: T:NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy
  parent: NMF.Expressions.IncrementalizationConfiguration
  name: IncrementalizationStrategy
  nameWithType: IncrementalizationStrategy
  fullName: NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy
- uid: NMF.Expressions.IncrementalizationConfiguration.MethodConfiguration
  commentId: T:NMF.Expressions.IncrementalizationConfiguration.MethodConfiguration
  parent: NMF.Expressions.IncrementalizationConfiguration
  name: MethodConfiguration
  nameWithType: MethodConfiguration
  fullName: NMF.Expressions.IncrementalizationConfiguration.MethodConfiguration
- uid: NMF.Expressions.IncrementalizationConfiguration
  commentId: N:NMF.Expressions.IncrementalizationConfiguration
  name: NMF.Expressions.IncrementalizationConfiguration
  nameWithType: NMF.Expressions.IncrementalizationConfiguration
  fullName: NMF.Expressions.IncrementalizationConfiguration
  spec.csharp:
  - uid: NMF
    name: NMF
  - name: .
  - uid: NMF.Expressions
    name: Expressions
  - name: .
  - uid: NMF.Expressions.IncrementalizationConfiguration
    name: IncrementalizationConfiguration
  spec.vb:
  - uid: NMF
    name: NMF
  - name: .
  - uid: NMF.Expressions
    name: Expressions
  - name: .
  - uid: NMF.Expressions.IncrementalizationConfiguration
    name: IncrementalizationConfiguration
