### YamlMime:ManagedReference
items:
- uid: NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy
  commentId: T:NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy
  id: IncrementalizationStrategy
  parent: NMF.Expressions.IncrementalizationConfiguration
  children:
  - NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy.ArgumentPromotion
  - NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy.InstructionLevel
  - NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy.ListenRepositoryChanges
  - NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy.UseAugmentation
  langs:
  - csharp
  - vb
  name: IncrementalizationStrategy
  nameWithType: IncrementalizationStrategy
  fullName: NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy
  type: Enum
  source:
    remote:
      path: Expressions/Expressions.Configuration/IncrementalizationConfiguration/IncrementalizationStrategy.cs
      branch: master
      repo: https://github.com/NMFCode/NMF.git
    id: IncrementalizationStrategy
    path: src/Expressions/Expressions.Configuration/IncrementalizationConfiguration/IncrementalizationStrategy.cs
    startLine: 35
  assemblies:
  - NMF.Expressions.Configuration
  namespace: NMF.Expressions.IncrementalizationConfiguration
  summary: "\nDenotes the different possibilities for a function incrementalization\n"
  example: []
  syntax:
    content: >-
      [ModelRepresentationClass("http://nmf.codeplex.com/incrementalizationConfig#//IncrementalizationStrategy/")]

      public enum IncrementalizationStrategy
    content.vb: >-
      <ModelRepresentationClass("http://nmf.codeplex.com/incrementalizationConfig#//IncrementalizationStrategy/")>

      Public Enum IncrementalizationStrategy
  attributes:
  - type: NMF.Models.ModelRepresentationClassAttribute
    ctor: NMF.Models.ModelRepresentationClassAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: http://nmf.codeplex.com/incrementalizationConfig#//IncrementalizationStrategy/
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy.InstructionLevel
  commentId: F:NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy.InstructionLevel
  id: InstructionLevel
  parent: NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy
  langs:
  - csharp
  - vb
  name: InstructionLevel
  nameWithType: IncrementalizationStrategy.InstructionLevel
  fullName: NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy.InstructionLevel
  type: Field
  source:
    remote:
      path: Expressions/Expressions.Configuration/IncrementalizationConfiguration/IncrementalizationStrategy.cs
      branch: master
      repo: https://github.com/NMFCode/NMF.git
    id: InstructionLevel
    path: src/Expressions/Expressions.Configuration/IncrementalizationConfiguration/IncrementalizationStrategy.cs
    startLine: 41
  assemblies:
  - NMF.Expressions.Configuration
  namespace: NMF.Expressions.IncrementalizationConfiguration
  summary: "\nDenotes that functions should be incrementalized on instruction-level\n"
  example: []
  syntax:
    content: InstructionLevel = 0
    return:
      type: NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy.ArgumentPromotion
  commentId: F:NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy.ArgumentPromotion
  id: ArgumentPromotion
  parent: NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy
  langs:
  - csharp
  - vb
  name: ArgumentPromotion
  nameWithType: IncrementalizationStrategy.ArgumentPromotion
  fullName: NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy.ArgumentPromotion
  type: Field
  source:
    remote:
      path: Expressions/Expressions.Configuration/IncrementalizationConfiguration/IncrementalizationStrategy.cs
      branch: master
      repo: https://github.com/NMFCode/NMF.git
    id: ArgumentPromotion
    path: src/Expressions/Expressions.Configuration/IncrementalizationConfiguration/IncrementalizationStrategy.cs
    startLine: 45
  assemblies:
  - NMF.Expressions.Configuration
  namespace: NMF.Expressions.IncrementalizationConfiguration
  summary: "\nDenotes that functions should be incrementalized by promoting cross-references to arguments\n"
  example: []
  syntax:
    content: ArgumentPromotion = 1
    return:
      type: NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy.ListenRepositoryChanges
  commentId: F:NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy.ListenRepositoryChanges
  id: ListenRepositoryChanges
  parent: NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy
  langs:
  - csharp
  - vb
  name: ListenRepositoryChanges
  nameWithType: IncrementalizationStrategy.ListenRepositoryChanges
  fullName: NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy.ListenRepositoryChanges
  type: Field
  source:
    remote:
      path: Expressions/Expressions.Configuration/IncrementalizationConfiguration/IncrementalizationStrategy.cs
      branch: master
      repo: https://github.com/NMFCode/NMF.git
    id: ListenRepositoryChanges
    path: src/Expressions/Expressions.Configuration/IncrementalizationConfiguration/IncrementalizationStrategy.cs
    startLine: 49
  assemblies:
  - NMF.Expressions.Configuration
  namespace: NMF.Expressions.IncrementalizationConfiguration
  summary: "\nDenotes that functions should be incrementalized by listening to repository changes\n"
  example: []
  syntax:
    content: ListenRepositoryChanges = 2
    return:
      type: NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy.UseAugmentation
  commentId: F:NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy.UseAugmentation
  id: UseAugmentation
  parent: NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy
  langs:
  - csharp
  - vb
  name: UseAugmentation
  nameWithType: IncrementalizationStrategy.UseAugmentation
  fullName: NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy.UseAugmentation
  type: Field
  source:
    remote:
      path: Expressions/Expressions.Configuration/IncrementalizationConfiguration/IncrementalizationStrategy.cs
      branch: master
      repo: https://github.com/NMFCode/NMF.git
    id: UseAugmentation
    path: src/Expressions/Expressions.Configuration/IncrementalizationConfiguration/IncrementalizationStrategy.cs
    startLine: 53
  assemblies:
  - NMF.Expressions.Configuration
  namespace: NMF.Expressions.IncrementalizationConfiguration
  summary: "\nDenotes that functions should be incrementalized by augmentations\n"
  example: []
  syntax:
    content: UseAugmentation = 3
    return:
      type: NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: NMF.Expressions.IncrementalizationConfiguration
  commentId: N:NMF.Expressions.IncrementalizationConfiguration
  name: NMF.Expressions.IncrementalizationConfiguration
  nameWithType: NMF.Expressions.IncrementalizationConfiguration
  fullName: NMF.Expressions.IncrementalizationConfiguration
- uid: NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy
  commentId: T:NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy
  parent: NMF.Expressions.IncrementalizationConfiguration
  name: IncrementalizationStrategy
  nameWithType: IncrementalizationStrategy
  fullName: NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy
