### YamlMime:ManagedReference
items:
- uid: NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy
  commentId: T:NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy
  id: IncrementalizationStrategy
  parent: NMF.Expressions.IncrementalizationConfiguration
  children:
  - NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy.ArgumentPromotion
  - NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy.InstructionLevel
  - NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy.ListenRepositoryChanges
  - NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy.UseAugmentation
  langs:
  - csharp
  - vb
  name: IncrementalizationStrategy
  nameWithType: IncrementalizationStrategy
  fullName: NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy
  type: Enum
  source:
    id: IncrementalizationStrategy
    path: C:\Users\hinkel\source\repos\NMFdocs\src\Expressions\Expressions.Configuration\IncrementalizationConfiguration\IncrementalizationStrategy.cs
    startLine: 35
  assemblies:
  - NMF.Expressions.Configuration
  namespace: NMF.Expressions.IncrementalizationConfiguration
  summary: Denotes the different possibilities for a function incrementalization
  example: []
  syntax:
    content: >-
      [ModelRepresentationClass("http://nmf.codeplex.com/incrementalizationConfig#//IncrementalizationStrategy/")]

      public enum IncrementalizationStrategy
    content.vb: >-
      <ModelRepresentationClass("http://nmf.codeplex.com/incrementalizationConfig#//IncrementalizationStrategy/")>

      Public Enum IncrementalizationStrategy
  extensionMethods:
  - NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy.NMF.Expressions.Linq.ExpressionExtensions.AsOne``1
  attributes:
  - type: NMF.Models.ModelRepresentationClassAttribute
    ctor: NMF.Models.ModelRepresentationClassAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: http://nmf.codeplex.com/incrementalizationConfig#//IncrementalizationStrategy/
- uid: NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy.InstructionLevel
  commentId: F:NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy.InstructionLevel
  id: InstructionLevel
  parent: NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy
  langs:
  - csharp
  - vb
  name: InstructionLevel
  nameWithType: IncrementalizationStrategy.InstructionLevel
  fullName: NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy.InstructionLevel
  type: Field
  source:
    id: InstructionLevel
    path: C:\Users\hinkel\source\repos\NMFdocs\src\Expressions\Expressions.Configuration\IncrementalizationConfiguration\IncrementalizationStrategy.cs
    startLine: 41
  assemblies:
  - NMF.Expressions.Configuration
  namespace: NMF.Expressions.IncrementalizationConfiguration
  summary: Denotes that functions should be incrementalized on instruction-level
  example: []
  syntax:
    content: InstructionLevel = 0
    return:
      type: NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy
- uid: NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy.ArgumentPromotion
  commentId: F:NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy.ArgumentPromotion
  id: ArgumentPromotion
  parent: NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy
  langs:
  - csharp
  - vb
  name: ArgumentPromotion
  nameWithType: IncrementalizationStrategy.ArgumentPromotion
  fullName: NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy.ArgumentPromotion
  type: Field
  source:
    id: ArgumentPromotion
    path: C:\Users\hinkel\source\repos\NMFdocs\src\Expressions\Expressions.Configuration\IncrementalizationConfiguration\IncrementalizationStrategy.cs
    startLine: 45
  assemblies:
  - NMF.Expressions.Configuration
  namespace: NMF.Expressions.IncrementalizationConfiguration
  summary: Denotes that functions should be incrementalized by promoting cross-references to arguments
  example: []
  syntax:
    content: ArgumentPromotion = 1
    return:
      type: NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy
- uid: NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy.ListenRepositoryChanges
  commentId: F:NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy.ListenRepositoryChanges
  id: ListenRepositoryChanges
  parent: NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy
  langs:
  - csharp
  - vb
  name: ListenRepositoryChanges
  nameWithType: IncrementalizationStrategy.ListenRepositoryChanges
  fullName: NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy.ListenRepositoryChanges
  type: Field
  source:
    id: ListenRepositoryChanges
    path: C:\Users\hinkel\source\repos\NMFdocs\src\Expressions\Expressions.Configuration\IncrementalizationConfiguration\IncrementalizationStrategy.cs
    startLine: 49
  assemblies:
  - NMF.Expressions.Configuration
  namespace: NMF.Expressions.IncrementalizationConfiguration
  summary: Denotes that functions should be incrementalized by listening to repository changes
  example: []
  syntax:
    content: ListenRepositoryChanges = 2
    return:
      type: NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy
- uid: NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy.UseAugmentation
  commentId: F:NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy.UseAugmentation
  id: UseAugmentation
  parent: NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy
  langs:
  - csharp
  - vb
  name: UseAugmentation
  nameWithType: IncrementalizationStrategy.UseAugmentation
  fullName: NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy.UseAugmentation
  type: Field
  source:
    id: UseAugmentation
    path: C:\Users\hinkel\source\repos\NMFdocs\src\Expressions\Expressions.Configuration\IncrementalizationConfiguration\IncrementalizationStrategy.cs
    startLine: 53
  assemblies:
  - NMF.Expressions.Configuration
  namespace: NMF.Expressions.IncrementalizationConfiguration
  summary: Denotes that functions should be incrementalized by augmentations
  example: []
  syntax:
    content: UseAugmentation = 3
    return:
      type: NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy
references:
- uid: NMF.Expressions.IncrementalizationConfiguration
  commentId: N:NMF.Expressions.IncrementalizationConfiguration
  href: NMF.html
  name: NMF.Expressions.IncrementalizationConfiguration
  nameWithType: NMF.Expressions.IncrementalizationConfiguration
  fullName: NMF.Expressions.IncrementalizationConfiguration
  spec.csharp:
  - uid: NMF
    name: NMF
    href: NMF.html
  - name: .
  - uid: NMF.Expressions
    name: Expressions
    href: NMF.Expressions.html
  - name: .
  - uid: NMF.Expressions.IncrementalizationConfiguration
    name: IncrementalizationConfiguration
    href: NMF.Expressions.IncrementalizationConfiguration.html
  spec.vb:
  - uid: NMF
    name: NMF
    href: NMF.html
  - name: .
  - uid: NMF.Expressions
    name: Expressions
    href: NMF.Expressions.html
  - name: .
  - uid: NMF.Expressions.IncrementalizationConfiguration
    name: IncrementalizationConfiguration
    href: NMF.Expressions.IncrementalizationConfiguration.html
- uid: NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy.NMF.Expressions.Linq.ExpressionExtensions.AsOne``1
  commentId: M:NMF.Expressions.Linq.ExpressionExtensions.AsOne``1(``0)
  parent: NMF.Expressions.Linq.ExpressionExtensions
  definition: NMF.Expressions.Linq.ExpressionExtensions.AsOne``1(``0)
  href: NMF.Expressions.Linq.ExpressionExtensions.html#NMF_Expressions_Linq_ExpressionExtensions_AsOne__1___0_
  name: AsOne<IncrementalizationStrategy>(IncrementalizationStrategy)
  nameWithType: ExpressionExtensions.AsOne<IncrementalizationStrategy>(IncrementalizationStrategy)
  fullName: NMF.Expressions.Linq.ExpressionExtensions.AsOne<NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy>(NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy)
  nameWithType.vb: ExpressionExtensions.AsOne(Of IncrementalizationStrategy)(IncrementalizationStrategy)
  fullName.vb: NMF.Expressions.Linq.ExpressionExtensions.AsOne(Of NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy)(NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy)
  name.vb: AsOne(Of IncrementalizationStrategy)(IncrementalizationStrategy)
  spec.csharp:
  - uid: NMF.Expressions.Linq.ExpressionExtensions.AsOne``1(NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy)
    name: AsOne
    href: NMF.Expressions.Linq.ExpressionExtensions.html#NMF_Expressions_Linq_ExpressionExtensions_AsOne__1___0_
  - name: <
  - uid: NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy
    name: IncrementalizationStrategy
    href: NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy.html
  - name: '>'
  - name: (
  - uid: NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy
    name: IncrementalizationStrategy
    href: NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy.html
  - name: )
  spec.vb:
  - uid: NMF.Expressions.Linq.ExpressionExtensions.AsOne``1(NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy)
    name: AsOne
    href: NMF.Expressions.Linq.ExpressionExtensions.html#NMF_Expressions_Linq_ExpressionExtensions_AsOne__1___0_
  - name: (
  - name: Of
  - name: " "
  - uid: NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy
    name: IncrementalizationStrategy
    href: NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy.html
  - name: )
  - name: (
  - uid: NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy
    name: IncrementalizationStrategy
    href: NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy.html
  - name: )
- uid: NMF.Expressions.Linq.ExpressionExtensions.AsOne``1(``0)
  commentId: M:NMF.Expressions.Linq.ExpressionExtensions.AsOne``1(``0)
  href: NMF.Expressions.Linq.ExpressionExtensions.html#NMF_Expressions_Linq_ExpressionExtensions_AsOne__1___0_
  name: AsOne<T>(T)
  nameWithType: ExpressionExtensions.AsOne<T>(T)
  fullName: NMF.Expressions.Linq.ExpressionExtensions.AsOne<T>(T)
  nameWithType.vb: ExpressionExtensions.AsOne(Of T)(T)
  fullName.vb: NMF.Expressions.Linq.ExpressionExtensions.AsOne(Of T)(T)
  name.vb: AsOne(Of T)(T)
  spec.csharp:
  - uid: NMF.Expressions.Linq.ExpressionExtensions.AsOne``1(``0)
    name: AsOne
    href: NMF.Expressions.Linq.ExpressionExtensions.html#NMF_Expressions_Linq_ExpressionExtensions_AsOne__1___0_
  - name: <
  - name: T
  - name: '>'
  - name: (
  - name: T
  - name: )
  spec.vb:
  - uid: NMF.Expressions.Linq.ExpressionExtensions.AsOne``1(``0)
    name: AsOne
    href: NMF.Expressions.Linq.ExpressionExtensions.html#NMF_Expressions_Linq_ExpressionExtensions_AsOne__1___0_
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
  - name: (
  - name: T
  - name: )
- uid: NMF.Expressions.Linq.ExpressionExtensions
  commentId: T:NMF.Expressions.Linq.ExpressionExtensions
  parent: NMF.Expressions.Linq
  href: NMF.Expressions.Linq.ExpressionExtensions.html
  name: ExpressionExtensions
  nameWithType: ExpressionExtensions
  fullName: NMF.Expressions.Linq.ExpressionExtensions
- uid: NMF.Expressions.Linq
  commentId: N:NMF.Expressions.Linq
  href: NMF.html
  name: NMF.Expressions.Linq
  nameWithType: NMF.Expressions.Linq
  fullName: NMF.Expressions.Linq
  spec.csharp:
  - uid: NMF
    name: NMF
    href: NMF.html
  - name: .
  - uid: NMF.Expressions
    name: Expressions
    href: NMF.Expressions.html
  - name: .
  - uid: NMF.Expressions.Linq
    name: Linq
    href: NMF.Expressions.Linq.html
  spec.vb:
  - uid: NMF
    name: NMF
    href: NMF.html
  - name: .
  - uid: NMF.Expressions
    name: Expressions
    href: NMF.Expressions.html
  - name: .
  - uid: NMF.Expressions.Linq
    name: Linq
    href: NMF.Expressions.Linq.html
- uid: NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy
  commentId: T:NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy
  parent: NMF.Expressions.IncrementalizationConfiguration
  href: NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy.html
  name: IncrementalizationStrategy
  nameWithType: IncrementalizationStrategy
  fullName: NMF.Expressions.IncrementalizationConfiguration.IncrementalizationStrategy
